/* Generated by MIPSduino Assembler (MicroCoreASM) */
#ifndef __PROGRAM_H__
#define __PROGRAM_H__

#include <stdint.h>

const uint32_t program[] = {
    0x24080001,
    0x24090008,
    0x240a0000,
    0x24020004,
    0x3c011001,
    0x34240000,
    0x0000000c,
    0x24020001,
    0x00082021,
    0x0000000c,
    0x24020004,
    0x3c011001,
    0x34240012,
    0x0000000c,
    0x00084040,
    0x214a0001,
    0x0149082a,
    0x1420fff1,
    0x2402000a,
    0x0000000c
};

const uint32_t program_len = 20;

#endif
