/* Generated by IronCore MIPS-X Toolchain */
#ifndef __PROGRAM_H__
#define __PROGRAM_H__

#include <stdint.h>

const uint32_t program[] = {
    0x24020004,
    0x3c011001,
    0x34240000,
    0x0000000c,
    0x2402000a,
    0x0000000c
};

const uint32_t program_len = 6;

#endif
